kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certificateIssuerName }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.requestSize }}
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.originServer.protocol }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingressVirtualHost }}
    secretName: {{ .Values.serviceName }}-tls-secret
  rules:
  - host: {{ .Values.ingressVirtualHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: {{ .Values.originServer.port }}
