apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.originServer.address }}
  ports:
  - port: {{ .Values.originServer.port }}
